name: Trigger NCCM Update on trunk updates

on:
  push:
    branches:
      - add/dispatch-on-trunk

jobs:
  trigger-nccm-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger NCCM Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.NCCM_ACCESS_TOKEN }}
          repository: Automattic/newspack-custom-content-migrator
          event-type: update-nmt-dependency
