name: Run Unit Tests

on: [ pull_request ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: wordpress_test
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, mysqli
          ini-values: |
            memory_limit=2G
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Download WordPress for unit tests
        run: bash bin/install-wp-tests.sh ${{ env.DB_DATABASE }} ${{ env.DB_USER }} ${{ env.DB_USER }} 127.0.0.1:3306 latest true

      - name: Run phpunit
        run: composer run phpunit
